### PR TITLE
Added rootless podman documentation to "Running our Containers".

### PR DESCRIPTION
**Pull request by N3WK1D**
Please feel free to offer feedback.

### CODE REVIEW

**Comment by Roxedus** [comment]
This should stress that rootless is not a Linuxserver supported setup, the first sentence is close to implying otherwise. 

Sorry for not commenting sooner.

**Comment by N3WK1D** [comment]
Hey, no worries. We all have lives to live. Made some changes. What do you think?

**Comment by Roxedus** [comment]
LGTM, but I want a onceover from @thespad too.

**Review by thespad — APPROVED** [review]
Sorry, I completely missed that this was waiting on me. I'm fine with the content, ideally I'd like to add some info on rootless *docker* as well but I don't have time to write it at the moment so I'll append it later.

**Comment by N3WK1D** [comment]
Given how easy-to-use docker is with lsio containers, this config doesn't make sense. More steps, same gain.

Closing for being unnecessary verbage.

**Pull request closed without merging**
