### PR TITLE
Future proof list of supported dns providers

### PR DESCRIPTION
**Pull request by Solsmed**
Relates to https://github.com/linuxserver/docker-documentation/issues/117

### CODE REVIEW

**Review by aptalca — APPROVED** [review]
Looks good. Thanks

**Comment by Solsmed** [comment]
Thanks, @aptalca! This was my first open-source project contribution 🍾

**Comment by aptalca** [comment]
Hopefully the first of many, right? 😉

**Comment by Solsmed** [comment]
The gates are opened 😎

**Pull request merged**
